### ISSUE TITLE
使用cpca过程中，报错缺少某些库，如下

### ISSUE THREAD

**Issue by yanjinping-pig** [DQinYuan/chinese_province_city_area_mapper#107]
Traceback (most recent call last):
  File "D:\pythonProject\huafen.py", line 2, in <module>
    import cpca
  File "D:\Python-3.9\lib\site-packages\cpca\__init__.py", line 7, in <module>
    from .matcher import Matcher
  File "D:\Python-3.9\lib\site-packages\cpca\matcher.py", line 1, in <module>
    import ahocorasick
ModuleNotFoundError: No module named 'ahocorasick'

**Comment by MrCat9** [comment]
这个是AC自动机的python实现库。
```
conda install -c http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/ pyahocorasick  # 先安装pyahocorasick
pip install -i https://pypi.doubanio.com/simple/ cpca
```
